"""ajout de last_fragment_earned_at sur users

Revision ID: 197500b4ec50
Revises: 9f4c2a7b1d6e
Create Date: 2026-09-01 10:53:49.842086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '197500b4ec50'
down_revision = '9f4c2a7b1d6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_fragment_earned_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_fragment_earned_at')

    # ### end Alembic commands ###
