"""ajout de avatar et bio a users

Revision ID: 1da056188a15
Revises: 416cdec16b94
Create Date: 2026-08-12 17:52:46.339163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1da056188a15'
down_revision = '416cdec16b94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.String(length=280), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('bio')
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###
