"""ajout du cadrage de l'image de couverture d'album

Revision ID: 31d84dfdb01a
Revises: 857ab8189b9d
Create Date: 2026-09-10 15:00:10.017443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31d84dfdb01a'
down_revision = '857ab8189b9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_x', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('image_y', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('image_scale', sa.Float(), nullable=False, server_default='100'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.drop_column('image_scale')
        batch_op.drop_column('image_y')
        batch_op.drop_column('image_x')

    # ### end Alembic commands ###
