"""ajout du suivi de progression et choix de scene pour les jeux speciaux

Revision ID: 45e9b549ca37
Revises: 9f93de1720d7
Create Date: 2026-09-25 11:30:46.930761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45e9b549ca37'
down_revision = '9f93de1720d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cache_cine_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scene_id', sa.Integer(), nullable=False),
    sa.Column('best_found_count', sa.Integer(), nullable=False),
    sa.Column('best_total', sa.Integer(), nullable=False),
    sa.Column('best_tier', sa.String(length=20), nullable=False),
    sa.Column('times_played', sa.Integer(), nullable=False),
    sa.Column('last_played_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['cache_cine_scenes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'scene_id', name='uq_cache_cine_progress_user_scene')
    )
    op.create_table('mystery_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('best_found_count', sa.Integer(), nullable=False),
    sa.Column('best_total', sa.Integer(), nullable=False),
    sa.Column('best_tier', sa.String(length=20), nullable=False),
    sa.Column('times_played', sa.Integer(), nullable=False),
    sa.Column('last_played_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['mystery_cases.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'case_id', name='uq_mystery_progress_user_case')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mystery_progress')
    op.drop_table('cache_cine_progress')
    # ### end Alembic commands ###
