"""supprime requires_account

Revision ID: 45f669c2c02f
Revises: 962af9872671
Create Date: 2026-09-24 09:42:07.659083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45f669c2c02f'
down_revision = '962af9872671'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_column('requires_account')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requires_account', sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
