"""ajout du compteur de bonnes reponses pour les tickets d'or

Revision ID: 464dd536880f
Revises: b364521d5f43
Create Date: 2026-09-07 14:29:33.619370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '464dd536880f'
down_revision = 'b364521d5f43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # server_default='0' : le compteur démarre à zéro pour tout le monde
        # (y compris les comptes déjà actifs) plutôt que d'être rétro-rempli
        # depuis l'historique des tentatives — comme pour le palier de série
        # de connexion, aucun crédit rétroactif n'est accordé sur ce nouveau
        # chemin d'obtention d'un Ticket d'Or.
        batch_op.add_column(sa.Column('total_correct_answers', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('total_correct_answers')

    # ### end Alembic commands ###
