"""ajout de content_type sur question

Revision ID: 52d3ad0dcab3
Revises: 9544b92c019c
Create Date: 2026-08-27 11:17:56.461263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52d3ad0dcab3'
down_revision = '9544b92c019c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 1er batch : la colonne est creee avec un server_default, ce qui remplit
    # les lignes existantes lors de la recopie de la table par SQLite.
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_type', sa.String(length=10),
                                      nullable=False, server_default='film'))

    # 2e batch : le server_default n'etait la que pour la migration, on le retire.
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('content_type',
                              existing_type=sa.String(length=10),
                              existing_nullable=False,
                              server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_column('content_type')

    # ### end Alembic commands ###
