"""ajout de earned_xp sur attempts

Revision ID: 53dc09a277e0
Revises: d5f2a91c7b08
Create Date: 2026-08-30 09:54:07.579302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53dc09a277e0'
down_revision = 'd5f2a91c7b08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default requis : les lignes déjà en base n'ont pas de valeur pour
    # cette nouvelle colonne NOT NULL. 0 est correct pour l'historique, puisque
    # ces tentatives passées n'ont jamais eu leur XP tracée individuellement.
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('earned_xp', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.drop_column('earned_xp')

    # ### end Alembic commands ###
