"""ajout de last_fragment_at sur user_characters

Revision ID: 857ab8189b9d
Revises: fe9cd87e5e5f
Create Date: 2026-09-10 14:03:01.599930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '857ab8189b9d'
down_revision = 'fe9cd87e5e5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_fragment_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_characters', schema=None) as batch_op:
        batch_op.drop_column('last_fragment_at')

    # ### end Alembic commands ###
