"""ajout de current_question_index et table game_answers

Revision ID: 881c47c0696c
Revises: 22350b794b8f
Create Date: 2026-08-25 16:35:06.623186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '881c47c0696c'
down_revision = '22350b794b8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_index', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_session_id'], ['game_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_answers')
    # ### end Alembic commands ###
