"""refonte scene mystere en questions independantes par zone

Revision ID: b364521d5f43
Revises: e1efd12027e7
Create Date: 2026-09-07 11:35:58.466522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b364521d5f43'
down_revision = 'e1efd12027e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mystery_hints')
    with op.batch_alter_table('mystery_cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_limit_seconds', sa.Integer(), nullable=False, server_default='240'))

    with op.batch_alter_table('mystery_options', schema=None) as batch_op:
        # Table vide à ce stade (aucun cas Scène Mystère réel encore créé) :
        # server_default purement syntaxique, requis par SQLite pour ajouter
        # une colonne NOT NULL même sans ligne existante à retro-remplir.
        batch_op.add_column(sa.Column('zone_id', sa.Integer(), nullable=False, server_default='0'))
        batch_op.create_foreign_key("fk_mystery_options_zone_id", 'mystery_zones', ['zone_id'], ['id'])
        batch_op.drop_column('case_id')

    with op.batch_alter_table('mystery_zones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clue_text', sa.String(length=255), nullable=False, server_default=''))
        batch_op.drop_column('is_correct')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mystery_zones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_correct', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('clue_text')

    with op.batch_alter_table('mystery_options', schema=None) as batch_op:
        batch_op.add_column(sa.Column('case_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key("fk_mystery_options_case_id", 'mystery_cases', ['case_id'], ['id'])
        batch_op.drop_column('zone_id')

    with op.batch_alter_table('mystery_cases', schema=None) as batch_op:
        batch_op.drop_column('time_limit_seconds')

    op.create_table('mystery_hints',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('case_id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.VARCHAR(length=255), nullable=False),
    sa.Column('order_index', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['mystery_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
