"""ajout de la table works

Revision ID: bf129d47f2b1
Revises: 45f669c2c02f
Create Date: 2026-09-24 15:27:34.073074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf129d47f2b1'
down_revision = '45f669c2c02f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('works',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('poster_url', sa.String(length=255), nullable=True),
    sa.Column('genres', sa.JSON(), nullable=False),
    sa.Column('saga', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tmdb_id', 'content_type', name='uq_work_tmdb')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('work_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_questions_work_id_works', 'works', ['work_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_questions_work_id_works', type_='foreignkey')
        batch_op.drop_column('work_id')

    op.drop_table('works')
    # ### end Alembic commands ###
