"""ajout du casting sur works

Revision ID: c2dc5952436e
Revises: 45e9b549ca37
Create Date: 2026-09-28 09:28:08.862929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2dc5952436e'
down_revision = '45e9b549ca37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default requis : colonne NOT NULL ajoutée à une table works déjà
    # peuplée (échouerait sinon en production, cf. convention du projet).
    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cast', sa.JSON(), nullable=False, server_default='[]'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.drop_column('cast')

    # ### end Alembic commands ###
