"""ajout manquant de current_question_index sur game_sessions

Revision ID: cacfa9776ad7
Revises: 881c47c0696c
Create Date: 2026-08-26 11:27:05.587895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cacfa9776ad7'
down_revision = '881c47c0696c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_question_index', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_sessions', schema=None) as batch_op:
        batch_op.drop_column('current_question_index')

    # ### end Alembic commands ###
