"""trois mini missions quotidiennes au lieu d'un defi unique

Revision ID: dae0f8efe589
Revises: b3d4e5f6a7b8
Create Date: 2026-09-04 14:03:37.043695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dae0f8efe589'
down_revision = 'b3d4e5f6a7b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_challenges', schema=None) as batch_op:
        # server_default indispensable : les lignes déjà en base (anciens
        # défis à un seul par jour) doivent recevoir une valeur, pas NULL,
        # pour une colonne NOT NULL ajoutée après coup. slot=0 les traite
        # comme la première (et jusqu'ici unique) mission de leur journée.
        batch_op.add_column(sa.Column('slot', sa.Integer(), nullable=False, server_default='0'))
        batch_op.drop_constraint(batch_op.f('uq_user_challenge_date'), type_='unique')
        batch_op.create_unique_constraint('uq_user_challenge_date_slot', ['user_id', 'challenge_date', 'slot'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_challenges', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_challenge_date_slot', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_user_challenge_date'), ['user_id', 'challenge_date'])
        batch_op.drop_column('slot')

    # ### end Alembic commands ###
