"""refonte scene mystere en zones sur une image

Revision ID: e1efd12027e7
Revises: 99a061f9aaef
Create Date: 2026-09-07 11:10:45.996461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1efd12027e7'
down_revision = '99a061f9aaef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mystery_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('pos_x', sa.Float(), nullable=False),
    sa.Column('pos_y', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['mystery_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('mystery_scenes')
    with op.batch_alter_table('mystery_cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mystery_cases', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    op.create_table('mystery_scenes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('case_id', sa.INTEGER(), nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_correct', sa.BOOLEAN(), nullable=False),
    sa.Column('order_index', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['mystery_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('mystery_zones')
    # ### end Alembic commands ###
