"""ajout de coins, equipped_title sur users et table user_titles

Revision ID: f7ced1523cb0
Revises: 8a4b35e58e53
Create Date: 2026-08-07 09:07:34.848978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7ced1523cb0'
down_revision = '8a4b35e58e53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_titles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title_code', sa.String(length=50), nullable=False),
    sa.Column('purchassed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coins', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('equipped_title', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('equipped_title')
        batch_op.drop_column('coins')

    op.drop_table('user_titles')
    # ### end Alembic commands ###
